"""Load one landed CSV into raw_zone: TRUNCATE staging, bulk load, MERGE, TRUNCATE, one commit.

The Azure counterpart of ``glue-jobs/redshift-raw-ingestion.py``. Same five steps in the same
order, same staging tables, same MERGE -- generated by the AWS job's own ``merge_sql()`` from the
AWS job's own column lists -- against Azure SQL Database instead of Redshift::

    credit-mailer-lab/raw_landing_zone/credit_mailer_db/<table>/data.csv    written by the extractor
      ->  TRUNCATE  raw_zone.tmp_<table>
      ->  load      into raw_zone.tmp_<table>        client-side: blob -> pyodbc fast_executemany
      ->  MERGE     into raw_zone.<table>             on the table's own key
      ->  TRUNCATE  raw_zone.tmp_<table>
      ->  conn.commit()                              ONE atomic unit, on this engine for real

Why a staging table and a MERGE rather than loading straight into raw_zone, why the staging table
is truncated BEFORE the load as well as after, and why the zero-row run needs no branch: all as the
AWS job argues them, and all unchanged. What follows is only what the move to T-SQL changed.

THE BULK LOAD IS CLIENT-SIDE, AND THAT WAS MEASURED RATHER THAN ASSUMED
-----------------------------------------------------------------------
The faithful port of Redshift's ``COPY ... FROM 's3://...'`` is a server-side load: ``BULK INSERT``
or ``OPENROWSET(BULK ...)`` through an external data source over the blob container, so the rows go
storage -> engine and never through this process. That was tried first, against Azurite, on SQL
Server 2022 CU27, with a database-scoped SAS credential:

*   ``LOCATION = 'http://azurite:10000/devstoreaccount1/credit-mailer-lab'`` -- the data source is
    created, and the load fails with error 12704, "Bad or inaccessible location specified in
    external data source". Azurite's path-style URL is not a location SQL Server will read.
*   the same over ``https://`` -- error 12704 again.
*   a virtual-host ``https://devstoreaccount1.blob.core.windows.net/...`` location -- accepted, and
    then resolved against the public Azure endpoint rather than the emulator (OS error 12175).
*   ``abs://`` through data virtualization -- error 46530; the image ships without PolyBase.

So the load reads the blob in this process and inserts it with pyodbc's ``fast_executemany``,
which sends the parameter arrays in bulk rather than a round trip per row: the whole
``client_attributes`` state -- 58,168 rows read, bound, merged and committed -- takes under two
seconds against the local container. On Azure SQL Database proper the server-side route
is available -- ``BULK INSERT ... WITH (DATA_SOURCE = ...)`` over a real ``*.blob.core.windows.net``
container -- and this function is the one to swap; the MERGE and everything after it would not
change. The client-side load was kept for the local run because it is the path that runs, and a
load path that only runs in the cloud is a load path the tests cannot hold to anything.

What client-side buys, and it is worth having: the CSV header is in this process's hands, so it is
CHECKED against the target's column list before a row is inserted. Redshift's COPY maps by
position and skips the header unread -- the AWS job says so, and says nothing there can fix it.
Here a reordered extract is refused by name instead of loading every flag into its neighbour.

AN EMPTY FIELD MUST BECOME NULL HERE, BECAUSE T-SQL WILL NOT DO IT
------------------------------------------------------------------
``csv.DictWriter`` writes a NULL as an empty field. Redshift's COPY with ``EMPTYASNULL`` reads that
back as NULL for every type, and DuckDB does the same without being asked. T-SQL does not:
``CAST('' AS SMALLINT)`` is **0** -- measured on the container -- and ``CAST('' AS DECIMAL(5,2))``
is an error. So every empty field is turned into ``None`` in Python before it is bound as a
parameter, for every column, which is ``EMPTYASNULL`` applied by hand. Get this wrong in the
direction T-SQL leans and wave 1's fourteen NULL treatment flags -- 69,636 cells of "this arm did
not exist yet" -- load as zeros, and every count downstream still adds up.

pyodbc's fast path is the second guard rather than the first. It converts the text client-side
against the parameter types the server describes, and it refuses an empty string for a SMALLINT
("Invalid character value for cast specification") rather than zeroing it -- but relying on that
would be relying on a driver detail to hold up a data rule. The None is sent explicitly.

THREE THINGS SQL SERVER ENFORCES THAT REDSHIFT DID NOT, ALL IN THE PORT'S FAVOUR
---------------------------------------------------------------------------------
1.  **VARCHAR(16).** A 17-character ``race`` fails the load. Under ``fast_executemany`` the refusal
    comes from pyodbc before the server sees the row -- it sizes its parameter buffer from the
    column width the server reports, so the declared width is what is being enforced -- and a
    plain INSERT gets error 2628 from the server itself. Either way nothing is truncated and the
    transaction rolls back. The AWS job could only state the headroom; the tests here load 16 and
    17 characters and assert both outcomes.
2.  **PRIMARY KEY.** Redshift accepts the declaration and enforces nothing. Here a landing file
    holding one ``(client_id, wave)`` twice reaches the MERGE through a keyless staging table, and
    the MERGE's second insert fails with error 2627. The MERGE is still what makes a re-run
    idempotent; the key is now a real second line behind it.
3.  **TRUNCATE is transactional.** On Redshift TRUNCATE commits, so the AWS job's load is three
    commits with boundaries at the two truncates, and its docstring spends a section on what that
    costs. Here TRUNCATE is logged and rolls back, so the whole load -- both truncates, the bulk
    insert and the MERGE -- is ONE unit ended by ``conn.commit()``. A failed MERGE leaves the
    staging table exactly as it was before the run, rows and all; a test asserts that with a
    sentinel row.

THE MERGE TEXT, AND THE ONE CHARACTER T-SQL ADDS
------------------------------------------------
The statement is ``merge_sql()`` from the AWS job plus a ``;``. T-SQL requires a MERGE to be
terminated -- without it the server raises error 10713, "A MERGE statement must be terminated by a
semi-colon" -- and the AWS generator omits it because neither Redshift nor DuckDB cares. Everything
else is accepted as written, including the target named in full in the ON clause
(``raw_zone.mail_offers.client_id = source.client_id``), which Redshift needs because it takes no
alias on a MERGE target.

TRANSACTION CONTROL
-------------------
One mechanism: pyodbc's implicit transaction, ended by ``conn.commit()`` or ``conn.rollback()``.
The AWS job's local path sends ``BEGIN TRANSACTION`` as text for DuckDB's sake; through pyodbc that
nests, and the commit that follows makes nothing durable. See ``azure_common.connect_sql()``.

    python python-jobs/azure-sql-raw-ingestion.py --self-check
    python python-jobs/azure-sql-raw-ingestion.py --table_name mail_offers
"""

import argparse
import csv
import io
import logging

import azure_common as az

LOG = logging.getLogger("azure_sql_raw_ingestion")

AWS = az.load_aws_job("redshift-raw-ingestion.py", "aws_redshift_raw_ingestion")
TABLES = AWS.TABLES
RAW_SCHEMA = AWS.RAW_SCHEMA
count_rows = AWS.count_rows


def merge_sql(table):
    """The AWS job's MERGE for `table`, terminated. The only change T-SQL requires of the text."""
    return AWS.merge_sql(table) + ";"


def staging_table(table):
    return "{0}.tmp_{1}".format(RAW_SCHEMA, table)


def insert_sql(table):
    """The parameterised INSERT the bulk load binds its rows to, in the table's declared order."""
    columns = TABLES[table]["columns"]
    return "INSERT INTO {0} ({1}) VALUES ({2})".format(
        staging_table(table), ", ".join(columns), ", ".join("?" for _ in columns))


def read_landing(container_client, table):
    """The landing blob's text. Read in full: the largest is about a megabyte."""
    return container_client.get_blob_client(az.landing_blob_name(table)) \
        .download_blob(encoding="utf-8").readall()


def parse_extract(table, text):
    """The CSV as a list of tuples in the table's column order, with every empty field as None.

    The header is compared with the column list rather than skipped: a COPY cannot do that, and
    a load that can should. An empty text -- a zero-byte blob -- is refused too, because the
    extractor writes a header even for zero rows, so a blob with no header is not something it
    wrote.
    """
    reader = csv.reader(io.StringIO(text, newline=""))
    header = next(reader, None)
    expected = list(TABLES[table]["columns"])
    if header is None:
        raise ValueError("the landing blob for {0} is empty -- not even a header. The extractor "
                         "writes one on every run, so this is not its output".format(table))
    if header != expected:
        raise ValueError("the landing blob for {0} has the header {1}; {2} declares {3}. The "
                         "load is positional, so a different order would load every column "
                         "into its neighbour".format(table, header, staging_table(table),
                                                     expected))
    rows = []
    for number, record in enumerate(reader, start=2):
        if len(record) != len(expected):
            raise ValueError("line {0} of {1}'s extract has {2} fields, not {3}"
                             .format(number, table, len(record), len(expected)))
        rows.append(tuple(None if field == "" else field for field in record))
    return rows


def bulk_load(cursor, table, rows):
    """Insert the parsed rows into the staging table with pyodbc's array binding.

    Values go as text and the server's declared types convert them -- the same division of labour
    as a COPY, where the file is text and the table decides what it means. An empty list is not
    sent at all: pyodbc refuses an empty parameter sequence, and run 4's header-only extract is
    the one run that produces one.
    """
    if not rows:
        LOG.info("0 rows to load into %s", staging_table(table))
        return 0
    cursor.fast_executemany = True
    cursor.executemany(insert_sql(table), rows)
    return len(rows)


def self_check():
    """Assert the generated SQL and the parser. No database, no network, no files."""
    # 1. The AWS job's own assertions about the split and its MERGE text: 32 + 7 columns
    #    accounting for all 37, keys matched and not assigned, INSERT and VALUES lined up.
    AWS.self_check()

    for table, spec in TABLES.items():
        merge = merge_sql(table)
        # 2. The terminator, which is the entire T-SQL change to the statement.
        assert merge.endswith(";") and not merge.endswith(";;"), \
            "{0}'s MERGE is not terminated exactly once".format(table)
        assert merge[:-1] == AWS.merge_sql(table), "the MERGE text drifted from the AWS job's"
        # 3. The INSERT binds one parameter per declared column, in declared order.
        insert = insert_sql(table)
        assert insert.count("?") == len(spec["columns"])
        assert "({0})".format(", ".join(spec["columns"])) in insert

    # 4. Empty fields are NULL, whatever the column; a zero stays a zero.
    header = ",".join(TABLES["client_attributes"]["columns"])
    rows = parse_extract("client_attributes", header + "\n1,,HIGH,0,,12,3\n")
    assert rows == [("1", None, "HIGH", "0", None, "12", "3")], rows

    # 5. A reordered header is refused rather than loaded positionally, and so is an empty blob.
    swapped = header.replace("female,edhi", "edhi,female")
    for bad in [swapped + "\n", ""]:
        try:
            parse_extract("client_attributes", bad)
        except ValueError:
            pass
        else:                                                       # pragma: no cover
            raise AssertionError("parse_extract accepted {0!r}".format(bad[:40]))

    # 6. Run 4: a header and nothing else parses to no rows, and needs no branch downstream.
    assert parse_extract("mail_offers", ",".join(TABLES["mail_offers"]["columns"]) + "\n") == []

    LOG.info("self-check passed: the AWS MERGE text plus its T-SQL terminator, one bound "
             "parameter per column, empty fields as NULL, and a reordered or empty extract "
             "refused before it reaches the warehouse")


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--table_name", "--table-name", dest="table_name",
                        choices=sorted(TABLES),
                        help="which landed extract to load. The choice sets the merge key: "
                             "(client_id, wave) for mail_offers, (client_id) for "
                             "client_attributes")
    parser.add_argument("--container", default=az.DEFAULT_CONTAINER,
                        help="landing-zone container (default: %(default)s)")
    parser.add_argument("--database", default=az.DEFAULT_DATABASE,
                        help="SQL database (default: %(default)s)")
    parser.add_argument("--self-check", action="store_true",
                        help="assert the generated SQL and the parser, then exit")
    args, _ = parser.parse_known_args()

    if args.self_check:
        self_check()
        return
    if not args.table_name:
        parser.error("--table_name is required unless --self-check")

    table = args.table_name
    staging = staging_table(table)
    target = "{0}.{1}".format(RAW_SCHEMA, table)

    # Read and parsed before the connection opens, so a missing blob or a bad header costs no
    # transaction at all and the warehouse is never touched.
    rows = parse_extract(table, read_landing(az.blob_container(args.container), table))
    LOG.info("loading %s: %s rows from %s/%s into %s", table, len(rows), args.container,
             az.landing_blob_name(table), target)

    conn = None
    try:
        conn = az.connect_sql(args.database)
        cursor = conn.cursor()
        # Before the load as well as after the merge -- the AWS job's fix (2). Here it is also
        # inside the transaction, so a failed run puts back whatever was in staging before it.
        az.run(cursor, "TRUNCATE TABLE {0}".format(staging), log=LOG)
        bulk_load(cursor, table, rows)
        staged = count_rows(cursor, staging, log=LOG)
        if staged == 0:
            LOG.info("0 rows staged: the extract was header-only, so the watermark had already "
                     "reached the last wave in the source and the merge below is a no-op")
        az.run(cursor, merge_sql(table), log=LOG)
        az.run(cursor, "TRUNCATE TABLE {0}".format(staging), log=LOG)
        held = count_rows(cursor, target, log=LOG)
        conn.commit()
        LOG.info("%s: %s rows staged and merged, %s rows now in %s -- one transaction",
                 table, staged, held, target)
    except Exception:
        if conn is not None:
            conn.rollback()
        raise
    finally:
        if conn is not None:
            conn.close()


if __name__ == "__main__":
    main()
